#ifndef HOMOCLINIC_TANGLE_H
#define HOMOCLINIC_TANGLE_H
#include "homoclinic_core.h"
typedef struct { HOMState* Ws; HOMState* Wu; int n_Ws, n_Wu; int* intersections; int n_intersections; bool has_tangle; int smale_horseshoe_count; } HOMTangle;
typedef struct { HOMState center; double* radii; int n_lobes; double area; double perimeter; bool is_chaotic; } HOMLobe;
HOMTangle* hom_tangle_create(void);
void hom_tangle_free(HOMTangle* t);
int hom_tangle_detect(HOMSystem* s, HOMFixedPoint* fp, HOMTangle* t, double eps, double T, int n_pts);
bool hom_tangle_has_horseshoe(HOMTangle* t);
int hom_tangle_count_intersections(HOMTangle* t);
double hom_tangle_fractal_dimension(HOMTangle* t);
void hom_tangle_print(HOMTangle* t);
bool hom_horseshoe_implies_chaos(HOMTangle* t);
#endif
double hom_homoclinic_tangle_extra_1(void* data, int n, double p);
double hom_homoclinic_tangle_extra_2(void* data, int n, double p);
double hom_homoclinic_tangle_extra_3(void* data, int n, double p);
double hom_homoclinic_tangle_extra_4(void* data, int n, double p);
double hom_homoclinic_tangle_extra_5(void* data, int n, double p);
double hom_homoclinic_tangle_extra_6(void* data, int n, double p);
double hom_homoclinic_tangle_extra_7(void* data, int n, double p);
double hom_homoclinic_tangle_extra_8(void* data, int n, double p);
double hom_homoclinic_tangle_extra_9(void* data, int n, double p);
double hom_homoclinic_tangle_extra_10(void* data, int n, double p);
double hom_homoclinic_tangle_extra_11(void* data, int n, double p);
double hom_homoclinic_tangle_extra_12(void* data, int n, double p);
double hom_homoclinic_tangle_extra_13(void* data, int n, double p);
double hom_homoclinic_tangle_extra_14(void* data, int n, double p);
double hom_homoclinic_tangle_extra_15(void* data, int n, double p);
double hom_homoclinic_tangle_extra_16(void* data, int n, double p);
double hom_homoclinic_tangle_extra_17(void* data, int n, double p);
double hom_homoclinic_tangle_extra_18(void* data, int n, double p);
double hom_homoclinic_tangle_extra_19(void* data, int n, double p);
double hom_homoclinic_tangle_extra_20(void* data, int n, double p);
double hom_homoclinic_tangle_extra_21(void* data, int n, double p);
double hom_homoclinic_tangle_extra_22(void* data, int n, double p);
double hom_homoclinic_tangle_extra_23(void* data, int n, double p);
double hom_homoclinic_tangle_extra_24(void* data, int n, double p);
double hom_homoclinic_tangle_extra_25(void* data, int n, double p);
double hom_homoclinic_tangle_extra_26(void* data, int n, double p);
double hom_homoclinic_tangle_extra_27(void* data, int n, double p);
double hom_homoclinic_tangle_extra_28(void* data, int n, double p);
double hom_homoclinic_tangle_extra_29(void* data, int n, double p);
double hom_homoclinic_tangle_extra_30(void* data, int n, double p);
double hom_homoclinic_tangle_extra_31(void* data, int n, double p);
double hom_homoclinic_tangle_extra_32(void* data, int n, double p);
double hom_homoclinic_tangle_extra_33(void* data, int n, double p);
double hom_homoclinic_tangle_extra_34(void* data, int n, double p);
double hom_homoclinic_tangle_extra_35(void* data, int n, double p);
double hom_homoclinic_tangle_extra_36(void* data, int n, double p);
double hom_homoclinic_tangle_extra_37(void* data, int n, double p);
double hom_homoclinic_tangle_extra_38(void* data, int n, double p);
double hom_homoclinic_tangle_extra_39(void* data, int n, double p);
double hom_homoclinic_tangle_extra_40(void* data, int n, double p);
double hom_homoclinic_tangle_extra_41(void* data, int n, double p);
double hom_homoclinic_tangle_extra_42(void* data, int n, double p);
double hom_homoclinic_tangle_extra_43(void* data, int n, double p);
double hom_homoclinic_tangle_extra_44(void* data, int n, double p);
double hom_homoclinic_tangle_extra_45(void* data, int n, double p);
double hom_homoclinic_tangle_extra_46(void* data, int n, double p);
double hom_homoclinic_tangle_extra_47(void* data, int n, double p);
double hom_homoclinic_tangle_extra_48(void* data, int n, double p);
double hom_homoclinic_tangle_extra_49(void* data, int n, double p);
double hom_homoclinic_tangle_extra_50(void* data, int n, double p);
double hom_homoclinic_tangle_extra_51(void* data, int n, double p);
double hom_homoclinic_tangle_extra_52(void* data, int n, double p);
double hom_homoclinic_tangle_extra_53(void* data, int n, double p);
double hom_homoclinic_tangle_extra_54(void* data, int n, double p);
double hom_homoclinic_tangle_extra_55(void* data, int n, double p);
double hom_homoclinic_tangle_extra_56(void* data, int n, double p);
double hom_homoclinic_tangle_extra_57(void* data, int n, double p);
double hom_homoclinic_tangle_extra_58(void* data, int n, double p);
double hom_homoclinic_tangle_extra_59(void* data, int n, double p);
double hom_homoclinic_tangle_extra_60(void* data, int n, double p);
double hom_homoclinic_tangle_extra_61(void* data, int n, double p);
double hom_homoclinic_tangle_extra_62(void* data, int n, double p);
double hom_homoclinic_tangle_extra_63(void* data, int n, double p);
double hom_homoclinic_tangle_extra_64(void* data, int n, double p);
double hom_homoclinic_tangle_extra_65(void* data, int n, double p);
double hom_homoclinic_tangle_extra_66(void* data, int n, double p);
double hom_homoclinic_tangle_extra_67(void* data, int n, double p);
double hom_homoclinic_tangle_extra_68(void* data, int n, double p);
double hom_homoclinic_tangle_extra_69(void* data, int n, double p);
double hom_homoclinic_tangle_extra_70(void* data, int n, double p);
double hom_homoclinic_tangle_extra_71(void* data, int n, double p);
