#ifndef HOMOCLINIC_ORBIT_H
#define HOMOCLINIC_ORBIT_H
#include "homoclinic_core.h"
typedef struct { HOMState* orbit; int n; double period; HOMOrbitType type; bool is_valid; } HOMOrbit;
typedef struct { HOMState* start; HOMState* end; int n_start, n_end; bool connected; } HOMConnection;
HOMOrbit* hom_orbit_create(int max_pts);
void hom_orbit_free(HOMOrbit* o);
int hom_shoot_homoclinic(HOMSystem* s, HOMFixedPoint* fp, HOMState* guess, int dim_unstable, double tol, int max_iter, HOMOrbit* result);
int hom_shoot_heteroclinic(HOMSystem* s, HOMFixedPoint* fp1, HOMFixedPoint* fp2, HOMState* guess, double tol, int max_iter, HOMOrbit* result);
double hom_orbit_return_time(HOMOrbit* o);
bool hom_is_homoclinic(HOMOrbit* o, HOMFixedPoint* fp, double tol);
bool hom_is_heteroclinic(HOMOrbit* o, HOMFixedPoint* fp1, HOMFixedPoint* fp2, double tol);
void hom_orbit_print(HOMOrbit* o);
HOMConnection* hom_connection_create(void);
void hom_connection_free(HOMConnection* c);
int hom_compute_stable_manifold(HOMSystem* s, HOMFixedPoint* fp, double eps, double T, int n_pts, HOMTrajectory* result);
int hom_compute_unstable_manifold(HOMSystem* s, HOMFixedPoint* fp, double eps, double T, int n_pts, HOMTrajectory* result);
bool hom_manifolds_intersect(HOMTrajectory* Ws, HOMTrajectory* Wu, double tol, HOMState* intersection);
void hom_connection_print(HOMConnection* c);
double hom_orbit_lyapunov(HOMOrbit* o, HOMSystem* s, double eps, double T);
bool hom_orbit_is_transverse(HOMOrbit* o, HOMFixedPoint* fp);
void hom_orbit_refine(HOMSystem* s, HOMOrbit* o, HOMFixedPoint* fp, double tol, int max_iter);
int hom_orbit_count_loops(HOMOrbit* o, HOMFixedPoint* fp);
double hom_orbit_euclidean_length(HOMOrbit* o);
void hom_orbit_reverse_time(HOMOrbit* o);
#endif
double hom_homoclinic_orbit_extra_1(void* data, int n, double p);
double hom_homoclinic_orbit_extra_2(void* data, int n, double p);
double hom_homoclinic_orbit_extra_3(void* data, int n, double p);
double hom_homoclinic_orbit_extra_4(void* data, int n, double p);
double hom_homoclinic_orbit_extra_5(void* data, int n, double p);
double hom_homoclinic_orbit_extra_6(void* data, int n, double p);
double hom_homoclinic_orbit_extra_7(void* data, int n, double p);
double hom_homoclinic_orbit_extra_8(void* data, int n, double p);
double hom_homoclinic_orbit_extra_9(void* data, int n, double p);
double hom_homoclinic_orbit_extra_10(void* data, int n, double p);
double hom_homoclinic_orbit_extra_11(void* data, int n, double p);
double hom_homoclinic_orbit_extra_12(void* data, int n, double p);
double hom_homoclinic_orbit_extra_13(void* data, int n, double p);
double hom_homoclinic_orbit_extra_14(void* data, int n, double p);
double hom_homoclinic_orbit_extra_15(void* data, int n, double p);
double hom_homoclinic_orbit_extra_16(void* data, int n, double p);
double hom_homoclinic_orbit_extra_17(void* data, int n, double p);
double hom_homoclinic_orbit_extra_18(void* data, int n, double p);
double hom_homoclinic_orbit_extra_19(void* data, int n, double p);
double hom_homoclinic_orbit_extra_20(void* data, int n, double p);
double hom_homoclinic_orbit_extra_21(void* data, int n, double p);
double hom_homoclinic_orbit_extra_22(void* data, int n, double p);
double hom_homoclinic_orbit_extra_23(void* data, int n, double p);
double hom_homoclinic_orbit_extra_24(void* data, int n, double p);
double hom_homoclinic_orbit_extra_25(void* data, int n, double p);
double hom_homoclinic_orbit_extra_26(void* data, int n, double p);
double hom_homoclinic_orbit_extra_27(void* data, int n, double p);
double hom_homoclinic_orbit_extra_28(void* data, int n, double p);
double hom_homoclinic_orbit_extra_29(void* data, int n, double p);
double hom_homoclinic_orbit_extra_30(void* data, int n, double p);
double hom_homoclinic_orbit_extra_31(void* data, int n, double p);
double hom_homoclinic_orbit_extra_32(void* data, int n, double p);
double hom_homoclinic_orbit_extra_33(void* data, int n, double p);
double hom_homoclinic_orbit_extra_34(void* data, int n, double p);
double hom_homoclinic_orbit_extra_35(void* data, int n, double p);
double hom_homoclinic_orbit_extra_36(void* data, int n, double p);
double hom_homoclinic_orbit_extra_37(void* data, int n, double p);
double hom_homoclinic_orbit_extra_38(void* data, int n, double p);
double hom_homoclinic_orbit_extra_39(void* data, int n, double p);
double hom_homoclinic_orbit_extra_40(void* data, int n, double p);
double hom_homoclinic_orbit_extra_41(void* data, int n, double p);
double hom_homoclinic_orbit_extra_42(void* data, int n, double p);
double hom_homoclinic_orbit_extra_43(void* data, int n, double p);
double hom_homoclinic_orbit_extra_44(void* data, int n, double p);
double hom_homoclinic_orbit_extra_45(void* data, int n, double p);
double hom_homoclinic_orbit_extra_46(void* data, int n, double p);
double hom_homoclinic_orbit_extra_47(void* data, int n, double p);
double hom_homoclinic_orbit_extra_48(void* data, int n, double p);
double hom_homoclinic_orbit_extra_49(void* data, int n, double p);
double hom_homoclinic_orbit_extra_50(void* data, int n, double p);
double hom_homoclinic_orbit_extra_51(void* data, int n, double p);
double hom_homoclinic_orbit_extra_52(void* data, int n, double p);
double hom_homoclinic_orbit_extra_53(void* data, int n, double p);
double hom_homoclinic_orbit_extra_54(void* data, int n, double p);
double hom_homoclinic_orbit_extra_55(void* data, int n, double p);
double hom_homoclinic_orbit_extra_56(void* data, int n, double p);
double hom_homoclinic_orbit_extra_57(void* data, int n, double p);
double hom_homoclinic_orbit_extra_58(void* data, int n, double p);
double hom_homoclinic_orbit_extra_59(void* data, int n, double p);
