#ifndef HOMOCLINIC_COMPUTATION_H
#define HOMOCLINIC_COMPUTATION_H
#include "homoclinic_core.h"
typedef struct { double* param_values; int n_params; int n_orbits; int param_idx; double p_min, p_max; bool found_bifurcation; double bifurcation_value; } HOMContinuation;
typedef struct { HOMState* initial_guess; int n_target; double convergence; int iterations; bool converged; } HOMShooting;
HOMContinuation* hom_continuation_create(int param_idx, double p_min, double p_max, int n_steps);
void hom_continuation_free(HOMContinuation* c);
int hom_continuation_run(HOMSystem* s, HOMFixedPoint* fp, HOMContinuation* c, double tol, int max_iter);
bool hom_continuation_detect_bifurcation(HOMContinuation* c, double th);
void hom_continuation_print(HOMContinuation* c);
HOMShooting* hom_shooting_create(HOMState* guess, int dim);
void hom_shooting_free(HOMShooting* sh);
int hom_shooting_solve(HOMSystem* s, HOMFixedPoint* fp, HOMShooting* sh, double tol, int max_iter);
bool hom_shooting_converged(HOMShooting* sh);
void hom_shooting_print(HOMShooting* sh);
int hom_find_homoclinic_bifurcation(HOMSystem* s, HOMFixedPoint* fp, double* pr, int np, double tol, double* bv);
bool hom_is_global_bifurcation(HOMSystem* s, HOMFixedPoint* fp, double tol);
#endif
double hom_homoclinic_computation_extra_1(void* data, int n, double p);
double hom_homoclinic_computation_extra_2(void* data, int n, double p);
double hom_homoclinic_computation_extra_3(void* data, int n, double p);
double hom_homoclinic_computation_extra_4(void* data, int n, double p);
double hom_homoclinic_computation_extra_5(void* data, int n, double p);
double hom_homoclinic_computation_extra_6(void* data, int n, double p);
double hom_homoclinic_computation_extra_7(void* data, int n, double p);
double hom_homoclinic_computation_extra_8(void* data, int n, double p);
double hom_homoclinic_computation_extra_9(void* data, int n, double p);
double hom_homoclinic_computation_extra_10(void* data, int n, double p);
double hom_homoclinic_computation_extra_11(void* data, int n, double p);
double hom_homoclinic_computation_extra_12(void* data, int n, double p);
double hom_homoclinic_computation_extra_13(void* data, int n, double p);
double hom_homoclinic_computation_extra_14(void* data, int n, double p);
double hom_homoclinic_computation_extra_15(void* data, int n, double p);
double hom_homoclinic_computation_extra_16(void* data, int n, double p);
double hom_homoclinic_computation_extra_17(void* data, int n, double p);
double hom_homoclinic_computation_extra_18(void* data, int n, double p);
double hom_homoclinic_computation_extra_19(void* data, int n, double p);
double hom_homoclinic_computation_extra_20(void* data, int n, double p);
double hom_homoclinic_computation_extra_21(void* data, int n, double p);
double hom_homoclinic_computation_extra_22(void* data, int n, double p);
double hom_homoclinic_computation_extra_23(void* data, int n, double p);
double hom_homoclinic_computation_extra_24(void* data, int n, double p);
double hom_homoclinic_computation_extra_25(void* data, int n, double p);
double hom_homoclinic_computation_extra_26(void* data, int n, double p);
double hom_homoclinic_computation_extra_27(void* data, int n, double p);
double hom_homoclinic_computation_extra_28(void* data, int n, double p);
double hom_homoclinic_computation_extra_29(void* data, int n, double p);
double hom_homoclinic_computation_extra_30(void* data, int n, double p);
double hom_homoclinic_computation_extra_31(void* data, int n, double p);
double hom_homoclinic_computation_extra_32(void* data, int n, double p);
double hom_homoclinic_computation_extra_33(void* data, int n, double p);
double hom_homoclinic_computation_extra_34(void* data, int n, double p);
double hom_homoclinic_computation_extra_35(void* data, int n, double p);
double hom_homoclinic_computation_extra_36(void* data, int n, double p);
double hom_homoclinic_computation_extra_37(void* data, int n, double p);
double hom_homoclinic_computation_extra_38(void* data, int n, double p);
double hom_homoclinic_computation_extra_39(void* data, int n, double p);
double hom_homoclinic_computation_extra_40(void* data, int n, double p);
double hom_homoclinic_computation_extra_41(void* data, int n, double p);
double hom_homoclinic_computation_extra_42(void* data, int n, double p);
double hom_homoclinic_computation_extra_43(void* data, int n, double p);
double hom_homoclinic_computation_extra_44(void* data, int n, double p);
double hom_homoclinic_computation_extra_45(void* data, int n, double p);
double hom_homoclinic_computation_extra_46(void* data, int n, double p);
double hom_homoclinic_computation_extra_47(void* data, int n, double p);
double hom_homoclinic_computation_extra_48(void* data, int n, double p);
double hom_homoclinic_computation_extra_49(void* data, int n, double p);
double hom_homoclinic_computation_extra_50(void* data, int n, double p);
double hom_homoclinic_computation_extra_51(void* data, int n, double p);
double hom_homoclinic_computation_extra_52(void* data, int n, double p);
double hom_homoclinic_computation_extra_53(void* data, int n, double p);
double hom_homoclinic_computation_extra_54(void* data, int n, double p);
double hom_homoclinic_computation_extra_55(void* data, int n, double p);
double hom_homoclinic_computation_extra_56(void* data, int n, double p);
double hom_homoclinic_computation_extra_57(void* data, int n, double p);
double hom_homoclinic_computation_extra_58(void* data, int n, double p);
double hom_homoclinic_computation_extra_59(void* data, int n, double p);
double hom_homoclinic_computation_extra_60(void* data, int n, double p);
double hom_homoclinic_computation_extra_61(void* data, int n, double p);
double hom_homoclinic_computation_extra_62(void* data, int n, double p);
double hom_homoclinic_computation_extra_63(void* data, int n, double p);
double hom_homoclinic_computation_extra_64(void* data, int n, double p);
double hom_homoclinic_computation_extra_65(void* data, int n, double p);
double hom_homoclinic_computation_extra_66(void* data, int n, double p);
double hom_homoclinic_computation_extra_67(void* data, int n, double p);
