#ifndef HOMOCLINIC_MELNIKOV_H
#define HOMOCLINIC_MELNIKOV_H
#include "homoclinic_core.h"
typedef double (*HOMForcingFunc)(double t, void* params);
typedef void (*HOMUnperturbedRHS)(HOMState x, HOMState* dx, void* params);
typedef struct { HOMForcingFunc forcing; void* forcing_params; HOMUnperturbedRHS rhs; void* rhs_params; double melnikov_integral; bool has_simple_zero; double* zero_crossings; int n_zeros; double bifurcation_threshold; HOMState* unperturbed_orbit; int n_orbit; } HOMMelnikov;
HOMMelnikov* hom_melnikov_create(HOMUnperturbedRHS rhs, void* rp, HOMForcingFunc f, void* fp);
void hom_melnikov_free(HOMMelnikov* m);
double hom_melnikov_integral(HOMMelnikov* m, HOMState* orbit, int n, double t0, double dt);
int hom_melnikov_find_zeros(HOMMelnikov* m, HOMState* orbit, int n, double dt, double tmin, double tmax, int ns);
bool hom_melnikov_has_transverse_intersection(HOMMelnikov* m);
double hom_melnikov_bifurcation_threshold(HOMMelnikov* m);
double hom_melnikov_eval_at(HOMMelnikov* m, double t0);
void hom_melnikov_print(HOMMelnikov* m);
bool hom_melnikov_chaos_prediction(HOMMelnikov* m, double th);
#endif
double hom_homoclinic_melnikov_extra_1(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_2(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_3(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_4(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_5(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_6(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_7(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_8(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_9(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_10(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_11(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_12(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_13(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_14(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_15(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_16(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_17(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_18(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_19(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_20(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_21(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_22(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_23(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_24(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_25(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_26(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_27(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_28(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_29(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_30(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_31(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_32(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_33(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_34(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_35(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_36(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_37(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_38(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_39(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_40(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_41(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_42(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_43(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_44(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_45(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_46(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_47(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_48(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_49(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_50(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_51(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_52(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_53(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_54(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_55(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_56(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_57(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_58(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_59(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_60(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_61(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_62(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_63(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_64(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_65(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_66(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_67(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_68(void* data, int n, double p);
double hom_homoclinic_melnikov_extra_69(void* data, int n, double p);
